travis:
  secure:
    BINSTAR_TOKEN: sWoCOgxRCskZPDdfhe8DtZxeT27ymVn1fP6J5WOSX2gwC+D2ssvBJFKalvTmMweJ8gVp67dMRS4qvoTDNnbLDd5P0f+SPc9EUFNOloWcsC+cQJNezy97vjGCOqtWZfMBR7eARZIQ5j9wZZlV1Rmkz8O2CuwFATw8vJP9teKK0GPycLyE8kppsneQyR7gdjQtUjo5njSXVbfJg3ca2ICfBSK1byLs995B+FOlnesnMblTivMrf+IxXsSgD90Sq5C8cMLMkmnmFxurhOkAa2BJI36VwFEAiD7DqM/dGIyhHShCIunL0OIAKYSg4ehygwJ1qEfHvMKCTk/S7vMvrhUHxGjSweco53RSFbLMVsrGeOEAuhn5XEAOWSFUlJBcwpTSH+mOVQ7ABH30bnDl3xK9klK+e3efhkAuY4g2FATgwovDCjWxEEJjR3XA5DvtE9h1RPch6xcqQ5yL0lV2nh5VdTru5zzx9iGCL1K6P9UYIxukI1DLX8AfZasLFM0i28lmf2ijnotIhdromNCYc3SUsvjb7WabKCO6X2vzJD/scrZNdZlStdnLQkQoYFEvBh8+LpBVezYM7stVliFmZ4/7wnV6Gz2dx9vYgGOfz+imsytqe8jF/vUFae7S2bs7eRi/pfrSCplfWct5+kljcp69cHnZfpRsgAzPArMrDF7peB4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
